version: '3.7'

services:

  nginx:
    image: nginx:1.19
    container_name: asyncweb-lb
    volumes:
      - ${PWD}/src/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - 8000:80
    networks:
      - aysncweb-net

#  netdata:
#    image: netdata/netdata
#    ports:
#      - 19999:19999
#    environment:
#      - DOCKER_HOST=proxy:2376
#      - DO_NOT_TRACK=1
#    cap_add:
#      - SYS_PTRACE
#    security_opt:
#      - apparmor:unconfined
#    restart: always
#    volumes:
#      - /etc/passwd:/host/etc/passwd:ro
#      - /etc/group:/host/etc/group:ro
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    depends_on:
#      - web
#    networks:
#      - aysncweb-net
#
  web:
#    build: .
    image: asyncweb:latest
    ports:
      - 8000:8000
    env_file:
      - ".env"
    volumes:
      - ${PWD}:/app
    networks:
      - aysncweb-net
    depends_on:
      - db
    command: '/app/bin/run.sh'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 60s
      timeout: 60s
      retries: 3
      start_period: 240s

  db:
    image: postgres:12.3-alpine
    container_name: asyncweb-db
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - ".env"
    networks:
      - aysncweb-net
    ports:
      - 5432:5432

volumes:
  db-data:

networks:
  aysncweb-net:
