version: '3.7'

services:

#  netdata:
#    image: netdata/netdata
#    ports:
#      - 19999:19999
#    environment:
#      - DOCKER_HOST=proxy:2376
#      - DO_NOT_TRACK=1
#    cap_add:
#      - SYS_PTRACE
#    security_opt:
#      - apparmor:unconfined
#    restart: always
#    volumes:
#      - /etc/passwd:/host/etc/passwd:ro
#      - /etc/group:/host/etc/group:ro
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    depends_on:
#      - web
#    networks:
#      - aysncweb
#
#  web:
##    build: .
#    image: asyncweb:latest
#    ports:
#      - 8000:8000
#    environment:
#      - WORKDIR=/app
#      - WORKSPACE=${WORKSPACE}
#      - VIRTUAL_ENV=${VIRTUAL_ENV}
#      - DATABASE_URL=${DATABASE_URL}
#    command: '/app/bin/run.sh'
#    volumes:
#      - ${PWD}:/app
#    networks:
#      - aysncweb
#    depends_on:
#      - db

  db:
    image: postgres:12.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - aysncweb
    ports:
      - 5432:5432

volumes:
  db-data:

networks:
  aysncweb:
